version: '3.8'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    command: mongod --replSet rs0 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - ./mongo.key:/data/keyfile
      - mongo1_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo_network

  mongo2:
    image: mongo
    container_name: mongo2
    command: mongod --replSet rs0 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - ./mongo.key:/data/keyfile
      - mongo2_data:/data/db
    ports:
      - "27217:27017"
    networks:
      - mongo_network
  mongo3:
    image: mongo
    container_name: mongo3
    command: mongod --replSet rs0 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - ./mongo.key:/data/keyfile
      - mongo3_data:/data/db
    ports:
      - "27317:27017"
    networks:
      - mongo_network
networks:
  mongo_network:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: